const mongoose = require("mongoose");


const orderSchema = new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true,
        },
        city:{
            type:String,
            required:true,
        },
        state:{
            type:String,
            required:true,
        },
        country:{
            type:String,
            required:true,
        },
        pinCode:{
            type:Number,
            required:true,
        },
        phoneNo:{
            type:Number,
            required:true,

        },
    },
        orderItems:[
            {
                name:{
                    type:String,
                    required:true,
                },
                price:{
                    type:Number,
                    required:true,
                },
                quantity:{
                    type:Number,
                    required:true,
                },
                image:{
                    type:String,
                    required:true,
                },
                food:{
                    type:mongoose.Schema.ObjectId,
                    ref:"Food",
                    required:true,
                },
            },
        ],
        user:{
            type:mongoose.Schema.ObjectId,
            ref:"User",
            required:true,
        },
        paymentInfo:{
            id:{
                type:String,
                required:true,               
            },
            status:{
                type:String,
                require:true,
            },  
        },
        PaidAt:{
            type:Date,
            require:true,
        },
        itemsPrice:{
            type:Number,
            require:true,
            default:0,
        },
        taxPrice:{
            type:Number,
            require:true,
            default:0,
        },
        shippingPrice:{
            type:Number,
            require:true,
            default:0,
        },
        totalPrice:{
            type:Number,
            require:true,
            default:0,
        },
        orderStatus:{
            type:String,
            required:true,
            default:"Processing",
        },
        deliveredAt:Date,
        createdAt:{
            type:Date,
            default:Date.now,
        },
});

module.exports=mongoose.model("Order",orderSchema);